//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_User_Menu
    {
        public string User_Id { get; set; }
        public int Menu_Id { get; set; }
        public Nullable<bool> TatCaQuyen { get; set; }
        public Nullable<bool> QuyenXem { get; set; }
        public Nullable<bool> QuyenThem { get; set; }
        public Nullable<bool> QuyenSua { get; set; }
        public Nullable<bool> QuyenXoa { get; set; }
        public Nullable<bool> QuyenLuu { get; set; }
        public Nullable<bool> QuyenIn { get; set; }
    
        public virtual AD_Menu AD_Menu { get; set; }
        public virtual AD_User AD_User { get; set; }
    }
}
