//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_User
    {
        public AD_User()
        {
            this.AD_User_Menu = new HashSet<AD_User_Menu>();
        }
    
        public string User_Id { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string ChucVu { get; set; }
        public string PhongBan { get; set; }
        public Nullable<bool> KhongDuocXoa { get; set; }
    
        public virtual ICollection<AD_User_Menu> AD_User_Menu { get; set; }
    }
}
