//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BM_Cot
    {
        public int BieuMau_Id { get; set; }
        public int Cot_Id { get; set; }
        public Nullable<int> Cot_ParentId { get; set; }
    }
}
