//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Code
    {
        public int CodeKind { get; set; }
        public int Code { get; set; }
        public string CodeKindName { get; set; }
        public string CodeName { get; set; }
    }
}
