//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Code
    {
        public int Id { get; set; }
        public int CodeValue { get; set; }
        public string CodeName { get; set; }
        public int CodeKind_Id { get; set; }
    
        public virtual DM_Code DM_Code1 { get; set; }
        public virtual DM_Code DM_Code2 { get; set; }
        public virtual DM_CodeKind DM_CodeKind { get; set; }
    }
}
