//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CodeKind
    {
        public int CodeKind_Id { get; set; }
        public string CodeKindName { get; set; }
        public Nullable<bool> KhongDuocXoa { get; set; }
    }
}
