//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CodeKind
    {
        public DM_CodeKind()
        {
            this.DM_Code = new HashSet<DM_Code>();
        }
    
        public int CodeKind_Id { get; set; }
        public string CodeKindName { get; set; }
    
        public virtual ICollection<DM_Code> DM_Code { get; set; }
    }
}
