//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DiaPhuong
    {
        public int DiaPhuong_Id { get; set; }
        public Nullable<int> DiaPhuong_ParentId { get; set; }
        public string TenDiaPhuong { get; set; }
        public string IDBanDo { get; set; }
        public string Loai { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string TelCode { get; set; }
    }
}
