//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_ChiTieu
    {
        public TK_ChiTieu()
        {
            this.TK_ThongKe = new HashSet<TK_ThongKe>();
        }
    
        public int ChiTieu_Id { get; set; }
        public Nullable<int> ChiTieu_ParentId { get; set; }
        public string TenChiTieu { get; set; }
        public Nullable<int> PhanHe_Id { get; set; }
        public Nullable<int> DonViTinh_Id { get; set; }
    
        public virtual DM_DonViTinh DM_DonViTinh { get; set; }
        public virtual ICollection<TK_ThongKe> TK_ThongKe { get; set; }
    }
}
