//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_DoiTuong
    {
        public TK_DoiTuong()
        {
            this.TK_ThongKe = new HashSet<TK_ThongKe>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string TenDoiTuong { get; set; }
        public Nullable<int> Nhom_Id { get; set; }
    
        public virtual ICollection<TK_ThongKe> TK_ThongKe { get; set; }
    }
}
