//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_ThongKe
    {
        public int ChiTieu_Id { get; set; }
        public int DoiTuong_Id { get; set; }
        public int KyBaoCao_Id { get; set; }
        public int Nhom_Id { get; set; }
        public int DiaPhuong_Id { get; set; }
        public string GiaTriThongKe { get; set; }
    
        public virtual DM_KyBaoCao DM_KyBaoCao { get; set; }
        public virtual DM_PhanHe DM_PhanHe { get; set; }
        public virtual TK_ChiTieu TK_ChiTieu { get; set; }
        public virtual TK_DoiTuong TK_DoiTuong { get; set; }
    }
}
