//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ThongKeNienGiam
    {
        public string TenKyBaoCao { get; set; }
        public string TenChiTieu { get; set; }
        public int ChiTieu_Id { get; set; }
        public int KyBaoCao_Id { get; set; }
        public int DiaPhuong_Id { get; set; }
        public string GiaTriThongKe { get; set; }
        public string TenDiaPhuong { get; set; }
    }
}
