//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDVTW_DBEntities : DbContext
    {
        public BDVTW_DBEntities()
            : base("name=BDVTW_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CapDiaPhuong> CapDiaPhuongs { get; set; }
        public DbSet<DanhMucChiTieu> DanhMucChiTieux { get; set; }
        public DbSet<DanhMucDiaPhuong> DanhMucDiaPhuongs { get; set; }
        public DbSet<DanhMucNhomChiTieu> DanhMucNhomChiTieux { get; set; }
        public DbSet<DiaPhuong> DiaPhuongs { get; set; }
        public DbSet<DMNghiepVu> DMNghiepVus { get; set; }
        public DbSet<DonViTinh> DonViTinhs { get; set; }
        public DbSet<KyBaoCao> KyBaoCaos { get; set; }
        public DbSet<NghiepVuChiTieu> NghiepVuChiTieux { get; set; }
        public DbSet<ThongKe> ThongKes { get; set; }
        public DbSet<VungDiaPhuong> VungDiaPhuongs { get; set; }
    }
}
