//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucDiaPhuong
    {
        public DanhMucDiaPhuong()
        {
            this.ThongKes = new HashSet<ThongKe>();
        }
    
        public int DiaPhuongID { get; set; }
        public Nullable<int> DiaPhuongIDCha { get; set; }
        public string TenDiaPhuong { get; set; }
        public string MaVungDP { get; set; }
        public string MaCapDP { get; set; }
        public string MoTaThem { get; set; }
        public string IDBanDo { get; set; }
    
        public virtual ICollection<ThongKe> ThongKes { get; set; }
    }
}
