//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMNghiepVu
    {
        public DMNghiepVu()
        {
            this.NghiepVuChiTieux = new HashSet<NghiepVuChiTieu>();
        }
    
        public System.Guid MaNghiepVu { get; set; }
        public string TenNghiepVu { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public string KhongSuDung { get; set; }
    
        public virtual ICollection<NghiepVuChiTieu> NghiepVuChiTieux { get; set; }
    }
}
