//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANN.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe
    {
        public System.Guid MaThongKe { get; set; }
        public int MaDiaPhuong { get; set; }
        public System.Guid MaChiTieu { get; set; }
        public string TenKyBaoCao { get; set; }
        public int CapSoLieu { get; set; }
        public string GiaTriThongKe { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public bool KhongSuDung { get; set; }
    
        public virtual DanhMucChiTieu DanhMucChiTieu { get; set; }
        public virtual DanhMucDiaPhuong DanhMucDiaPhuong { get; set; }
        public virtual DiaPhuong DiaPhuong { get; set; }
        public virtual KyBaoCao KyBaoCao { get; set; }
    }
}
